Github Actions

diff --git a/.github/workflows/true.yaml b/.github/workflows/true.yaml
--- a/.github/workflows/true.yaml
+++ b/.github/workflows/true.yaml
@@ -24,3 +24,31 @@ jobs:
             echo "PR Title: ${{ env.PR_TITLE }}"
             echo "PR Number: ${{ env.PR_NUMBER }}"
             echo "PR Author: ${{ env.PR_AUTHOR }}"
+        
+            - name: Get PR data
+            id: pr-data
+            uses: tj-actions/branch-names@v7.9
+            with:
+              github-token: ${{ secrets.GITHUB_TOKEN }}
+              pr-number: ${{ env.PR_NUMBER }}
+    
+        - name: Set PR base branch
+          run: echo "PR_BASE=${{ steps.pr-data.outputs.base }}" >> $GITHUB_ENV
+
+        - name: Set PR head branch
+          run: echo "PR_HEAD=${{ steps.pr-data.outputs.head }}" >> $GITHUB_ENV
+
+        - name: Determine action based on PR title
+          id: determine-action
+          run: |
+            if [[ "${{ env.PR_TITLE }}" == *"rebase:"* ]]; then
+                echo "ACTION=rebase" >> $GITHUB_ENV
+                elif [[ "${{ env.PR_TITLE }}" == *"merge:"* ]]; then
+                echo "ACTION=merge" >> $GITHUB_ENV
+            else
+                echo "No action required"
+                exit 1  # Exit with 1 to indicate that no action was necessary
+
+        - name: Print determined action
+          run: |
+            echo "Action determined: ${{ env.ACTION }}"
